### ISSUE TITLE
Milestone 3 Meeting Notes

### ISSUE THREAD

**Issue by williamxu7** [UBC-MDS/522-Group_30-Rockstars#33]
- Makefile

- Incorporate feedback from TAs

**Comment by danielon-5** [comment]
- Worked on the Makefile and changed the EDA targets as .svg instead of .png to be able to run it (reminder to change it back to .png).
- PR for the Makefile done
- Completed Makefile with every script
- Ran into some problems with 'pandoc' when running the final report
- Reinstalled rmarkdown and rlang to troubleshoot by using 'install.packages("rmarkdown")' and 'install.packages("rlang")'
- Fine tuned the Makefile to skip lines with backlashes ("\")
- Tested the Makefile with the two command lines 'make clean' and 'make all'
- Pushed the Makefile

Next meeting: Friday december 4th 10:30am PT
